* ~orgparser~ - A basic parser for Emacs Org mode files

This parser can parse basic Org mode files.

Parses Org files into a structure of ~seq[OrgNode]~ where an ~OrgNode~
can be:
#+begin_src nim
type
  OrgObj* = object
    case kind*: OrgNodeKind
    of ogText:
      text*: string
    of ogSection:
      sec*: Section # `* Foo \n some text \n` until next section
    of ogPropertyList:
      propList*: PropertyList # `:PROPERTIES:\n multiple ogProperty\n:END:`
    of ogProperty:
      prop*: Property # `:Foo: Bar`
    of ogBold, ogUnderlined, ogMonospace:
      emph*: string
    of ogLink:
      link*: Link # `[[https://...][foo]]`
    of ogPropertyStart, ogPropertyEnd: discard # no fields needed
  OrgNode* = ref OrgObj

  Property* = object
    key*: string
    value*: seq[OrgNode]

  PropertyList* = seq[Property]

  Link* = object
    link*: string
    desc*: string

  Section* = object
    title*: seq[OrgNode]
    level*: int # The section level (number of `*`)
    body*: seq[OrgNode]
#+end_src

** Note on implementation

I first just wanted to start with a super simple parser that works
line by line (i.e. ~startsWith~ for ~*~, ~:~ and the like), but
decided to got the lexer + parser combination route after all. Should
make it hopefully easier to add more advanced Org features in the
future, if desired.

** Why?

I wrote it because I use Org files to store all sorts of data. The
other day I thought I would change how I produce my CVs. Up to now I'm
still using Europass (https://europass.europa.eu/en), but I'm a bit
annoyed having to use an extremely slow web interface.

In the past I produced my CV using a custom LaTeX template, so I
thought why not go back to that kind of approach. But as a heavy Org
user nowadays, I felt like I'd want to store the actual *content* of
my CV in an Org file.

So the idea was born to:
- Org file with CV data
- Org file parser in Nim
- CV generator in Nim

The latter will be a simple API to stitch together all the desired
fields for a CV I want to produce. Then it will fill a LaTeX template
for one of the popular CV LaTeX templates (altacv, moderncv) and we're
done.
